### ISSUE TITLE
GopherJS Playground: Snippets are failing to load/save due to host name change.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs.github.io#20]
Snippets are currently not working. It seems that the hostname was previously `http://gopherjs.org`, but now it redirects to `http://www.gopherjs.org` (/cc @neelance, @ajhager), which results in the XHR failing:

`XMLHttpRequest cannot load http://snippets.gotools.org/p/D9L6MbPfE4. The 'Access-Control-Allow-Origin' header has a value 'http://gopherjs.org' that is not equal to the supplied origin. Origin 'http://www.gopherjs.org' is therefore not allowed access.`

**Comment by shurcooL** [comment]
Fixed with https://github.com/gopherjs/snippet-store/commit/06a3903a31c5861a1651ac2408751bc50e33c119 and deploying the new version of `snippet-store` that uses the `http://www.gopherjs.org` value for Access-Control-Allow-Origin.

**Comment by neelance** [comment]
Thx for the fix. What about putting the snippet store to a proper subdomain?

**Comment by shurcooL** [comment]
> What about putting the snippet store to a proper subdomain?

What do you have in mind?

**Comment by neelance** [comment]
Just `snippets.gopherjs.org` instead of `snippets.gotools.org`.

**Comment by shurcooL** [comment]
That is completely okay with me. It requires 3 steps:

- [ ] you map that subdomain to the same IP as the current one,
- [ ] I'll add a port 80 redirect for that subdomain host to snippet-server.
- [ ] change playground source to use new name and redeploy.

**Comment by neelance** [comment]
DNS record created.

**Comment by shurcooL** [comment]
Port 80 redirect rule added, http://snippets.gopherjs.org/p/D9L6MbPfE4 now works.

The last remaining step is to change `playground.go` source to use the new host, rebuild it, and deploy (by merging the PR).

**Comment by shurcooL** [comment]
Okay, I've started the last step in PR #21, but neelance/go-angularjs#7 needs to be merged first and then the playground needs to be rebuilt (run `update.sh`) before that PR can be merged.

**Comment by shurcooL** [comment]
Last step done in #21, and with that the transition to `snippets.gopherjs.org` instead of `snippets.gotools.org` is complete.
