### ISSUE TITLE
Proposal: Add goimports support to Playground (add/remove stdlib imports on Format).

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs.github.io#29]
The Go Playground has a checkbox to enable `goimports`-like fixing imports when pressing Format.

![image](https://cloud.githubusercontent.com/assets/1924134/8764176/e810fa50-2d7a-11e5-91af-9305457ce40f.png)

It's handy for fixing imports of standard library (fmt, io, bytes, etc.), and I'm used to it. I'd like to see it added to GopherJS Playground to make it better.

Any thoughts? Objections?

Should it be optional like on Go Playground or just always on?

I can volunteer to implement it. I already have implemented it locally, so it's just a matter of cleaning up the code and making a PR.

**Comment by dominikh** [comment]
If we're going to add it, make it optional please.

**Comment by shurcooL** [comment]
Ok. Is it ok for it to be on by default? I think on average more people would benefit from having it on rather than off.

**Comment by shurcooL** [comment]
+1 from me, I want this feature.

I'll likely make a PR for it soon.
