### ISSUE TITLE
Blog: make the RSS feed easier to find

### ISSUE THREAD

**Issue by zephyr** [gopherjs/gopherjs.github.io#56]
Right now, there is no indication on the [blog](http://www.gopherjs.org/blog/) (or anywhere else on the homepage) that there’s an RSS feed for the blog posts.

To subscribe to it, you have to go to the [source on github](https://github.com/gopherjs/gopherjs.github.io), see that there’s an `feed.xml` template, infere the correct feed url (`http://www.gopherjs.org/feed.xml`) and type it into your RSS reader. That’s not really userfriendly; in fact, i think that the majority of RSS users will just miss the feed.

To fix this, please add this line to the blog’s html `<header>`:

```
<link rel="alternate" type="application/atom+xml" title="GopherJS Blog" href="http://www.gopherjs.org/feed.xml" />
```

(some browsers are able to detect this), _and_ add to the html `<body>` something like:

```
<a href="http://www.gopherjs.org/feed.xml" target="_blank">
    <img src="https://upload.wikimedia.org/wikipedia/en/4/43/Feed-icon.svg" alt="RSS Feed of GopherJS"/>
</a>
```

It doesn't have to be big, but it should be somewhere for these who want to find it.

Thank you in ahead, this whole project is really great!

**Comment by shurcooL** [comment]
Thanks for reporting this issue and making a suggestion for how to fix it.

I don't use RSS, which is why I never noticed or paid attention to this. But I agree this is currently problematic and we can improve it.

**Comment by shurcooL** [comment]
@zephyr, I made PR #59 to resolve this. Does it look good to you?

**Comment by zephyr** [comment]
Yes, this looks very good to me. Thank you for the fix!
