### ISSUE TITLE
Website's license

### ISSUE THREAD

**Issue by vrok** [gopherjs/gopherjs.github.io#60]
First off, GopherJS is a great project, thank you for it!

GoperJS itself does have a license, but what about this repo? I'd like to re-use some of the code that can be found here, but I'm not sure if I can, and under what terms. It would be great if this information was available somewhere. Thanks!

**Comment by shurcooL** [comment]
I would imagine it should be a very permissive license, but I don't know exactly. /cc @neelance

**Comment by neelance** [comment]
Which code in particular?

**Comment by vrok** [comment]
@neelance The playground code.
I was thinking about using it to create a playground for [Have](github.com/vrok/have). It's a hobby project of mine, with no budget, and GopherJS would allow me to avoid running a farm of servers. 
Of course, it would contain a clear attribution to GopherJS (unless you wish otherwise).

**Comment by neelance** [comment]
I've added https://github.com/gopherjs/gopherjs.github.io/blob/master/playground/LICENSE, feel free to use it. :)

**Comment by vrok** [comment]
Awesome! Thank you!
