### ISSUE TITLE
Something went wrong with the theme of website?

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/gopherjs.github.io#63]
Check out http://www.gopherjs.org/ right now, it appears there's something wrong with the theme (CSS):

![image](https://cloud.githubusercontent.com/assets/1924134/21965842/00fd9c3e-db36-11e6-80fe-394f8cf554a8.png)

It used to be a dark theme and things were properly aligned, but they're not right now. I don't see any relevant [changes to the codebase](https://github.com/gopherjs/gopherjs.github.io/commits/master) recently, which is strange.

What could it be? Isn't the theme hard-coded into the files that are committed to this repo? I thought they were.

I don't see any errors loading content in the browser console.

/cc @neelance

**Comment by neelance** [comment]
Yeah, this is strange. Maybe GitHub changed something about the static site generator.

@shurcooL Do you have time to look into it / fix it?

**Comment by shurcooL** [comment]
I have time, but I don't know anything about this. Where should I start looking?

Do I need to be admin to see some sort of settings for the static site generation?

**Comment by shurcooL** [comment]
I looked in another repo where I am admin, and I see:

![image](https://cloud.githubusercontent.com/assets/1924134/21967549/59b9705c-db57-11e6-8dec-a3a8699c8be4.png)

Perhaps the theme dropdown box changed for this repo?

**Comment by neelance** [comment]
@shurcooL I've given you admin permissions.

**Comment by shurcooL** [comment]
The theme chooser for this repo says there's no theme picked.

I wonder if what happened is that some old theme was used, and it was removed by GitHub, and now there's no theme chosen? Or maybe there was never a theme chosen before either... I have no way of knowing.

FWIW, I found an old screenshot of the previous look, this is what it looked like:

![image](https://cloud.githubusercontent.com/assets/1924134/20073237/491bbbe0-a4e0-11e6-8f2d-05fdc2322231.png)

**Comment by shurcooL** [comment]
For people trying to use the playground, please use http://www.gopherjs.org/playground version until we find a way to resolve this CSS issue.

**Comment by shurcooL** [comment]
@neelance What are our next steps? We have https://medium.com/gopherjs now, but the (broken) website is still around.

**Comment by hajimehoshi** [comment]
What's the current status of this?

**Comment by neelance** [comment]
Now fixed via c78e393.
