### ISSUE TITLE
3rd-side packages

### ISSUE THREAD

**Issue by zgordan-vv** [gopherjs/gopherjs.github.io#71]
Is this a way to add some other packages to pkg folder, not only standard Go library ones?

**Comment by dmitshur** [comment]
Do you mean in a local copy of the playground? Yes, they're just compiled archive .a files being copied there. See `update.sh` file to see how the pkg directory is populated.

If you mean for https://gopherjs.github.io/playground/, that would require changing the scope of what's included in the playground.

**Comment by zgordan-vv** [comment]
Thank you, local copy works
