### ISSUE TITLE
Playground: Pull all packages in one XHR request

### ISSUE THREAD

**Issue by ajhager** [gopherjs/gopherjs.github.io#8]
There is a noticeable pause when loading the Playground, where an XHR request is being fired off for every .a file. While this is happening, the UI is frozen. It should be possible to gzip all of them and use just one request.

**Comment by broady** [comment]
Still a problem with HTTP/2 being a thing?

**Comment by shurcooL** [comment]
I think having packages be separate files is actually benefitial if we're using HTTP/2.

For that we need to support HTTPS and HTTP/2 on server. I know it's easy when hosting your own site with Let's Encrypt and a Go web server, but now sure about GitHub Pages.

Nevertheless, the difference between the two approaches is not very significant, and HTTP/2 is the future, so I think it's fine to assume we'll eventually have it, so there's no point in trying to switch to one large file now.

**Comment by shurcooL** [comment]
I'll close this because of above, but if someone has additional thoughts, feel free to comment or reopen.
